version: '3.8'
services:
  vector-store-api:
    build: 
      context: ./python_services
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEFAULT_VECTOR_STORE_ID=${DEFAULT_VECTOR_STORE_ID:-vs_687584b54f908191b0a21ffa42948fb5}
      - PYTHON_API_PORT=5001
    volumes:
      - ./uploads:/app/uploads:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3