# Replit Deployment Configuration for Investment Approval Portal

[deployment]
run = "npm start"
deploymentTarget = "cloudrun"

[[ports]]
containerPort = 5000
externalPort = 80

[env]
NODE_ENV = "production"